### ISSUE TITLE
R materials

### ISSUE THREAD

**Issue by nickeubank** [nickeubank/poli_sci_boot_camp#3]
My inclination is to find a ready-made (and hopefully iterated) set of R tutorials with exercises and focus on doing exercises in workshop. 

[This was made by a classmate of mine](https://sejdemyr.github.io/r-tutorials/basics/) from Stanford, and may be a great start, but open to other suggestions. I do think we can do better on exercises though...

**Comment by nickeubank** [comment]
another candidate: https://www.cyclismo.org/tutorial/R/index.html

**Comment by alexander-dan** [comment]
I vote for something done by a social scientist -- bound to be a bit better-suited to our needs.

**Comment by nickeubank** [comment]
Great call. OK, will start familiarizing myself and thinking about examples...

**Comment by alexander-dan** [comment]
Sorry, I just meant your classmate’s is probably better than the second option you sent over. Simon’s looks great!!!

**Comment by nickeubank** [comment]
? That's what I thought you were saying! I just haven't ever gone through Simon's in detail (I knew R before he wrote them), so need to revisit his organization. Also, I think his exercises are fine, but I think there are some ways we can make them even better (e.g. exercises where you give people all the code they need to do something, but put the lines of code in a jumbled order, a la #2 . Allows students to focus on control flow and organization rather than syntax.)

**Comment by nickeubank** [comment]
Interesting... I may actually prefer this tutorial to Simon's: https://www.cyclismo.org/tutorial/R/index.html Simon's is very detailed, but I think it may commit a cardinal sin of programming teaching: trying to teach the language too comprehensively from the bottom up. I think it's actually better to give a sense of the landscape without too much detail (in part to give people more buy-in and understand of what this tool does for them), *then* double back and fill in a lot. Looking at Simon's tutorials, I feel like I'd want to skip about half (like all the initial stuff on `seq` and `dplyr` tricks), which is hard to do if people are doing tutorials at home... 

[Sorry, just thinking aloud]

**Comment by nickeubank** [comment]
No, will mostly use Simons... but will skip dplyr section maybe? At least initially... Posting outline.
